#!/usr/bin/env bash

setup_remote () {
    name=$1
    url=$2

    echo ""
    echo "setup remote \"$name\" -> $url"
    git remote rm $name 2> /dev/null
    git remote add $name $url
    git fetch $name
}

setup_remote "demo" "zope@pi.4teamwork.ch:/home/zope/pi.4teamwork.ch/24-plone-jsonapi-demo"
